// Generated by gencpp from file battery_msgs/Battery_Srv.msg
// DO NOT EDIT!


#ifndef BATTERY_MSGS_MESSAGE_BATTERY_SRV_H
#define BATTERY_MSGS_MESSAGE_BATTERY_SRV_H

#include <ros/service_traits.h>


#include <battery_msgs/Battery_SrvRequest.h>
#include <battery_msgs/Battery_SrvResponse.h>


namespace battery_msgs
{

struct Battery_Srv
{

typedef Battery_SrvRequest Request;
typedef Battery_SrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Battery_Srv
} // namespace battery_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::battery_msgs::Battery_Srv > {
  static const char* value()
  {
    return "a5cba455e6c34810630dc8f80babd86a";
  }

  static const char* value(const ::battery_msgs::Battery_Srv&) { return value(); }
};

template<>
struct DataType< ::battery_msgs::Battery_Srv > {
  static const char* value()
  {
    return "battery_msgs/Battery_Srv";
  }

  static const char* value(const ::battery_msgs::Battery_Srv&) { return value(); }
};


// service_traits::MD5Sum< ::battery_msgs::Battery_SrvRequest> should match
// service_traits::MD5Sum< ::battery_msgs::Battery_Srv >
template<>
struct MD5Sum< ::battery_msgs::Battery_SrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::battery_msgs::Battery_Srv >::value();
  }
  static const char* value(const ::battery_msgs::Battery_SrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::battery_msgs::Battery_SrvRequest> should match
// service_traits::DataType< ::battery_msgs::Battery_Srv >
template<>
struct DataType< ::battery_msgs::Battery_SrvRequest>
{
  static const char* value()
  {
    return DataType< ::battery_msgs::Battery_Srv >::value();
  }
  static const char* value(const ::battery_msgs::Battery_SrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::battery_msgs::Battery_SrvResponse> should match
// service_traits::MD5Sum< ::battery_msgs::Battery_Srv >
template<>
struct MD5Sum< ::battery_msgs::Battery_SrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::battery_msgs::Battery_Srv >::value();
  }
  static const char* value(const ::battery_msgs::Battery_SrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::battery_msgs::Battery_SrvResponse> should match
// service_traits::DataType< ::battery_msgs::Battery_Srv >
template<>
struct DataType< ::battery_msgs::Battery_SrvResponse>
{
  static const char* value()
  {
    return DataType< ::battery_msgs::Battery_Srv >::value();
  }
  static const char* value(const ::battery_msgs::Battery_SrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BATTERY_MSGS_MESSAGE_BATTERY_SRV_H
